# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingitem',
            name='instruction',
            field=models.CharField(default=b'', max_length=250, verbose_name='Item instruction'),
        )
    ]
