# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_onboarding', '0002_auto_20160831_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingcontainer',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_onboarding_onboardingcontainer', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='onboardingitem',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_onboarding_onboardingitem', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
